server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: minilpa-web-backend
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    moe.sekiu.minilpa: ${LOG_LEVEL:INFO}
    org.springframework.web: ${WEB_LOG_LEVEL:WARN}
  file:
    name: ${LOG_FILE:./logs/backend.log}
    max-size: 10MB
    max-history: 30
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}

minilpa:
  command:
    timeout-ms: 30000
    download-timeout-ms: 120000
    retries: 2
  cache:
    profiles-ttl-ms: 2000
    notifications-ttl-ms: 2000
    chip-info-ttl-ms: 5000

