name: CI/CD - Deploy to Baota

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  JAVA_VERSION: '21'
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 检查目录结构
      run: |
        echo "=== 当前目录结构 ==="
        ls -la
        echo ""
        echo "=== 查找 web-backend ==="
        find . -name "web-backend" -type d 2>/dev/null || true
        echo ""
        echo "=== 查找 local-agent ==="
        find . -name "local-agent" -type d 2>/dev/null || true
        echo ""
        echo "=== 查找 web-frontend ==="
        find . -name "web-frontend" -type d 2>/dev/null || true
    
    - name: 设置 Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ env.JAVA_VERSION }}
    
    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: 构建后端服务
      run: |
        # 查找 web-backend 目录
        BACKEND_DIR=$(find . -type d -name "web-backend" | grep -v node_modules | head -1)
        if [ -z "$BACKEND_DIR" ]; then
          echo "错误: 找不到 web-backend 目录"
          exit 1
        fi
        echo "找到后端目录: $BACKEND_DIR"
        cd "$BACKEND_DIR"
        # 创建 gradlew 脚本（如果不存在）
        if [ ! -f "./gradlew" ]; then
          echo "创建 gradlew 脚本..."
          cat > gradlew << 'GRADLEW_EOF'
        #!/bin/sh
        APP_HOME=`pwd`
        CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
        exec java -Xmx64m -Xms64m -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
        GRADLEW_EOF
          chmod +x ./gradlew
        fi
        ./gradlew clean bootJar --no-daemon
    
    - name: 构建本地代理
      run: |
        # 查找 local-agent 目录
        AGENT_DIR=$(find . -type d -name "local-agent" | grep -v node_modules | head -1)
        if [ -z "$AGENT_DIR" ]; then
          echo "错误: 找不到 local-agent 目录"
          exit 1
        fi
        echo "找到代理目录: $AGENT_DIR"
        cd "$AGENT_DIR"
        # 检查并创建 gradle-wrapper.jar（如果不存在）
        if [ ! -f "./gradle/wrapper/gradle-wrapper.jar" ]; then
          echo "gradle-wrapper.jar 不存在，从 web-backend 复制..."
          mkdir -p ./gradle/wrapper
          # 查找 web-backend 目录中的 gradle-wrapper.jar
          BACKEND_WRAPPER=$(find . -path "*/web-backend/gradle/wrapper/gradle-wrapper.jar" 2>/dev/null | head -1)
          if [ -z "$BACKEND_WRAPPER" ]; then
            # 如果当前目录找不到，尝试在上级目录查找
            BACKEND_WRAPPER=$(find .. -path "*/web-backend/gradle/wrapper/gradle-wrapper.jar" 2>/dev/null | head -1)
          fi
          if [ -n "$BACKEND_WRAPPER" ] && [ -f "$BACKEND_WRAPPER" ]; then
            cp "$BACKEND_WRAPPER" ./gradle/wrapper/gradle-wrapper.jar
            echo "已从 web-backend 复制 gradle-wrapper.jar"
          else
            echo "错误: 找不到 gradle-wrapper.jar，尝试下载..."
            # 如果找不到，可以尝试下载（但这里先报错）
            echo "请确保 web-backend 目录中有 gradle-wrapper.jar"
            exit 1
          fi
        fi
        # 创建 gradlew 脚本（如果不存在）
        if [ ! -f "./gradlew" ]; then
          echo "创建 gradlew 脚本..."
          cat > gradlew << 'GRADLEW_EOF'
        #!/bin/sh
        APP_HOME=`pwd`
        CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
        exec java -Xmx64m -Xms64m -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
        GRADLEW_EOF
          chmod +x ./gradlew
        fi
        ./gradlew clean build --no-daemon
    
    - name: 构建前端
      run: |
        # 查找 web-frontend 目录
        FRONTEND_DIR=$(find . -type d -name "web-frontend" | grep -v node_modules | head -1)
        if [ -z "$FRONTEND_DIR" ]; then
          echo "错误: 找不到 web-frontend 目录"
          exit 1
        fi
        echo "找到前端目录: $FRONTEND_DIR"
        cd "$FRONTEND_DIR"
        npm ci
        npm run build
    
    - name: 准备部署文件
      run: |
        mkdir -p deploy-package/app
        mkdir -p deploy-package/frontend
        mkdir -p deploy-package/config
        
        # 查找并复制后端JAR（过滤掉 plain jar）
        BACKEND_DIR=$(find . -type d -name "web-backend" | grep -v node_modules | head -1)
        BACKEND_JAR=$(find "$BACKEND_DIR/build/libs" -name "*.jar" ! -name "*-plain.jar" | head -1)
        if [ -n "$BACKEND_JAR" ]; then
          cp "$BACKEND_JAR" deploy-package/app/minilpa-backend.jar
          echo "后端JAR已复制: $BACKEND_JAR"
        else
          echo "警告: 未找到后端JAR文件"
        fi
        
        # 查找并复制代理JAR（过滤掉 plain jar）
        AGENT_DIR=$(find . -type d -name "local-agent" | grep -v node_modules | head -1)
        AGENT_JAR=$(find "$AGENT_DIR/build/libs" -name "*.jar" ! -name "*-plain.jar" | head -1)
        if [ -n "$AGENT_JAR" ]; then
          cp "$AGENT_JAR" deploy-package/app/minilpa-agent.jar
          echo "代理JAR已复制: $AGENT_JAR"
        else
          echo "警告: 未找到代理JAR文件"
        fi
        
        # 查找并复制前端文件
        FRONTEND_DIR=$(find . -type d -name "web-frontend" | grep -v node_modules | head -1)
        if [ -d "$FRONTEND_DIR/dist" ]; then
          cp -r "$FRONTEND_DIR/dist"/* deploy-package/frontend/
          echo "前端文件已复制"
        else
          echo "警告: 未找到前端dist目录"
        fi
        
        # 查找并复制配置文件
        DEPLOY_DIR=$(find . -type d -name "deploy" | grep -v node_modules | head -1)
        if [ -d "$DEPLOY_DIR" ]; then
          cp "$DEPLOY_DIR/minilpa-backend.service" deploy-package/config/ 2>/dev/null || true
          cp "$DEPLOY_DIR/minilpa-agent.service" deploy-package/config/ 2>/dev/null || true
          cp "$DEPLOY_DIR/nginx.conf.example" deploy-package/config/ 2>/dev/null || true
          cp "$DEPLOY_DIR/update.sh" deploy-package/config/ 2>/dev/null || true
          cp "$DEPLOY_DIR/application-prod.yml" deploy-package/config/application.yml 2>/dev/null || true
          echo "配置文件已复制"
        fi
        
        # 创建部署脚本
        cat > deploy-package/deploy.sh << 'DEPLOYSCRIPT'
        #!/bin/bash
        set -e
        
        INSTALL_DIR="/www/wwwroot/minilpa"
        BACKUP_DIR="$INSTALL_DIR/backup/$(date +%Y%m%d_%H%M%S)"
        
        echo "=== MiniLPA 自动部署脚本 ==="
        
        # 检查是否为root用户
        if [ "$EUID" -ne 0 ]; then 
          echo "请使用 sudo 运行此脚本"
          exit 1
        fi
        
        # 1. 停止服务
        echo "1. 停止服务..."
        systemctl stop minilpa-backend 2>/dev/null || echo "   ⚠️  后端服务未运行或停止失败"
        systemctl stop minilpa-agent 2>/dev/null || echo "   ⚠️  代理服务未运行或停止失败"
        # 等待服务完全停止
        sleep 3
        # 确认服务已停止
        if systemctl is-active --quiet minilpa-backend; then
          echo "   ⚠️  后端服务仍在运行，强制停止..."
          systemctl kill -s SIGKILL minilpa-backend 2>/dev/null || true
          sleep 2
        fi
        if systemctl is-active --quiet minilpa-agent; then
          echo "   ⚠️  代理服务仍在运行，强制停止..."
          systemctl kill -s SIGKILL minilpa-agent 2>/dev/null || true
          sleep 2
        fi
        
        # 2. 备份旧文件
        echo "2. 备份旧文件..."
        mkdir -p "$BACKUP_DIR"
        if [ -f "$INSTALL_DIR/app/minilpa-backend.jar" ]; then
          cp "$INSTALL_DIR/app/minilpa-backend.jar" "$BACKUP_DIR/" 2>/dev/null || true
        fi
        if [ -f "$INSTALL_DIR/app/minilpa-agent.jar" ]; then
          cp "$INSTALL_DIR/app/minilpa-agent.jar" "$BACKUP_DIR/" 2>/dev/null || true
        fi
        
        # 3. 复制新文件
        echo "3. 复制新文件..."
        mkdir -p "$INSTALL_DIR/app" "$INSTALL_DIR/frontend" "$INSTALL_DIR/config" "$INSTALL_DIR/logs"
        
        # 复制JAR文件
        echo "检查部署包中的文件..."
        ls -la app/ 2>&1 || echo "⚠️ app 目录不存在"
        if [ -f "app/minilpa-backend.jar" ]; then
          cp app/minilpa-backend.jar "$INSTALL_DIR/app/" -f
          if [ -f "$INSTALL_DIR/app/minilpa-backend.jar" ]; then
            echo "   ✅ 后端JAR已更新: $(ls -lh "$INSTALL_DIR/app/minilpa-backend.jar" | awk '{print $5, $6, $7, $8}')"
          else
            echo "   ❌ 后端JAR复制失败"
          fi
        else
          echo "   ⚠️  未找到 app/minilpa-backend.jar"
        fi
        if [ -f "app/minilpa-agent.jar" ]; then
          cp app/minilpa-agent.jar "$INSTALL_DIR/app/" -f
          if [ -f "$INSTALL_DIR/app/minilpa-agent.jar" ]; then
            echo "   ✅ 代理JAR已更新: $(ls -lh "$INSTALL_DIR/app/minilpa-agent.jar" | awk '{print $5, $6, $7, $8}')"
          else
            echo "   ❌ 代理JAR复制失败"
          fi
        else
          echo "   ⚠️  未找到 app/minilpa-agent.jar"
        fi
        
        # 复制前端文件
        if [ -d "frontend" ]; then
          if [ -d "$INSTALL_DIR/frontend" ]; then
            mv "$INSTALL_DIR/frontend" "$BACKUP_DIR/frontend" 2>/dev/null || true
          fi
          cp -r frontend "$INSTALL_DIR/"
          echo "   ✅ 前端文件已更新"
        fi
        
        # 复制配置文件（可选，不覆盖现有配置）
        if [ -d "config" ]; then
          cp -r config/* "$INSTALL_DIR/config/" 2>/dev/null || true
        fi
        
        # 4. 设置权限
        echo "4. 设置权限..."
        chown -R www:www "$INSTALL_DIR" 2>/dev/null || chown -R $USER:$USER "$INSTALL_DIR"
        chmod 644 "$INSTALL_DIR/app"/*.jar 2>/dev/null || true
        
        # 5. 重启服务（确保使用新文件）
        echo "5. 重启服务..."
        systemctl daemon-reload 2>/dev/null || true
        systemctl enable minilpa-backend 2>/dev/null || true
        systemctl enable minilpa-agent 2>/dev/null || true
        # 使用 restart 而不是 start，确保服务真正重启
        echo "   重启后端服务..."
        systemctl restart minilpa-backend || systemctl start minilpa-backend
        echo "   重启代理服务..."
        systemctl restart minilpa-agent || systemctl start minilpa-agent
        
        sleep 3
        
        # 检查服务状态
        if systemctl is-active --quiet minilpa-backend; then
          echo "   ✅ 后端服务启动成功"
        else
          echo "   ⚠️  后端服务启动失败"
          echo "   查看日志: sudo journalctl -u minilpa-backend -n 50"
        fi
        
        if systemctl is-active --quiet minilpa-agent; then
          echo "   ✅ 代理服务启动成功"
        else
          echo "   ⚠️  代理服务启动失败"
          echo "   查看日志: sudo journalctl -u minilpa-agent -n 50"
        fi
        
        echo ""
        echo "=== 部署完成 ==="
        echo "备份位置: $BACKUP_DIR"
        DEPLOYSCRIPT
        chmod +x deploy-package/deploy.sh
        
        # 创建压缩包以便传输
        tar -czf deploy-package.tar.gz deploy-package/
        ls -lh deploy-package/
    
    - name: 部署到宝塔服务器
      uses: appleboy/scp-action@v0.1.7
      config:
        host: ${{ secrets.BAOTA_HOST }}
        username: ${{ secrets.BAOTA_USER }}
        key: ${{ secrets.BAOTA_SSH_KEY }}
        port: ${{ secrets.BAOTA_SSH_PORT || 22 }}
        source: "deploy-package.tar.gz"
        target: "/tmp"
        strip_components: 0
      continue-on-error: false
    
    - name: 解压并执行部署脚本
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BAOTA_HOST }}
        username: ${{ secrets.BAOTA_USER }}
        key: ${{ secrets.BAOTA_SSH_KEY }}
        port: ${{ secrets.BAOTA_SSH_PORT || 22 }}
        script: |
          cd /tmp
          echo "=== 步骤1: 检查部署包 ==="
          ls -lh deploy-package.tar.gz || { echo "错误: 找不到部署包"; exit 1; }
          echo ""
          echo "=== 步骤2: 解压部署包 ==="
          tar -xzf deploy-package.tar.gz
          cd deploy-package
          echo "部署包内容："
          ls -la
          echo ""
          echo "检查关键文件："
          ls -la app/ 2>&1 || echo "⚠️ app 目录不存在"
          ls -la frontend/ 2>&1 | head -5 || echo "⚠️ frontend 目录不存在"
          echo ""
          echo "=== 步骤3: 执行部署脚本 ==="
          sudo ./deploy.sh
          DEPLOY_EXIT_CODE=$?
          echo ""
          echo "=== 步骤4: 验证部署结果 ==="
          echo "检查部署目录："
          ls -la /www/wwwroot/minilpa/app/ 2>&1 || echo "⚠️ 部署目录不存在"
          echo ""
          if [ $DEPLOY_EXIT_CODE -eq 0 ]; then
            echo "✅ 部署脚本执行成功"
          else
            echo "❌ 部署脚本执行失败，退出码: $DEPLOY_EXIT_CODE"
            exit 1
          fi
          rm -rf /tmp/deploy-package /tmp/deploy-package.tar.gz
          echo "部署完成！"
    
    - name: 验证部署
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BAOTA_HOST }}
        username: ${{ secrets.BAOTA_USER }}
        key: ${{ secrets.BAOTA_SSH_KEY }}
        port: ${{ secrets.BAOTA_SSH_PORT || 22 }}
        script: |
          echo "=== 验证服务状态 ==="
          systemctl status minilpa-backend --no-pager -l || true
          systemctl status minilpa-agent --no-pager -l || true

