name: CI/CD - Deploy to Baota

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  JAVA_VERSION: '21'
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: 检查目录结构
      run: |
        echo "=== 当前目录结构 ==="
        ls -la
        echo ""
        echo "=== 查找 web-backend ==="
        find . -name "web-backend" -type d 2>/dev/null || true
        echo ""
        echo "=== 查找 local-agent ==="
        find . -name "local-agent" -type d 2>/dev/null || true
        echo ""
        echo "=== 查找 web-frontend ==="
        find . -name "web-frontend" -type d 2>/dev/null || true
    
    - name: 设置 Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ env.JAVA_VERSION }}
    
    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: 构建后端服务
      run: |
        # 查找 web-backend 目录
        BACKEND_DIR=$(find . -type d -name "web-backend" | grep -v node_modules | head -1)
        if [ -z "$BACKEND_DIR" ]; then
          echo "错误: 找不到 web-backend 目录"
          exit 1
        fi
        echo "找到后端目录: $BACKEND_DIR"
        cd "$BACKEND_DIR"
        # 如果存在 gradlew，使用它；否则使用 java 直接运行 wrapper jar
        if [ -f "./gradlew" ]; then
          chmod +x ./gradlew
          ./gradlew clean bootJar --no-daemon
        else
          # 使用 java 直接运行 Gradle wrapper
          java -jar gradle/wrapper/gradle-wrapper.jar clean bootJar --no-daemon
        fi
    
    - name: 构建本地代理
      run: |
        # 查找 local-agent 目录
        AGENT_DIR=$(find . -type d -name "local-agent" | grep -v node_modules | head -1)
        if [ -z "$AGENT_DIR" ]; then
          echo "错误: 找不到 local-agent 目录"
          exit 1
        fi
        echo "找到代理目录: $AGENT_DIR"
        cd "$AGENT_DIR"
        if [ -f "./gradlew" ]; then
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon
        else
          java -jar gradle/wrapper/gradle-wrapper.jar clean build --no-daemon
        fi
    
    - name: 构建前端
      run: |
        # 查找 web-frontend 目录
        FRONTEND_DIR=$(find . -type d -name "web-frontend" | grep -v node_modules | head -1)
        if [ -z "$FRONTEND_DIR" ]; then
          echo "错误: 找不到 web-frontend 目录"
          exit 1
        fi
        echo "找到前端目录: $FRONTEND_DIR"
        cd "$FRONTEND_DIR"
        npm ci
        npm run build
    
    - name: 准备部署文件
      run: |
        mkdir -p deploy-package/app
        mkdir -p deploy-package/frontend
        mkdir -p deploy-package/config
        
        # 查找并复制后端JAR（过滤掉 plain jar）
        BACKEND_DIR=$(find . -type d -name "web-backend" | grep -v node_modules | head -1)
        BACKEND_JAR=$(find "$BACKEND_DIR/build/libs" -name "*.jar" ! -name "*-plain.jar" | head -1)
        if [ -n "$BACKEND_JAR" ]; then
          cp "$BACKEND_JAR" deploy-package/app/minilpa-backend.jar
          echo "后端JAR已复制: $BACKEND_JAR"
        else
          echo "警告: 未找到后端JAR文件"
        fi
        
        # 查找并复制代理JAR（过滤掉 plain jar）
        AGENT_DIR=$(find . -type d -name "local-agent" | grep -v node_modules | head -1)
        AGENT_JAR=$(find "$AGENT_DIR/build/libs" -name "*.jar" ! -name "*-plain.jar" | head -1)
        if [ -n "$AGENT_JAR" ]; then
          cp "$AGENT_JAR" deploy-package/app/minilpa-agent.jar
          echo "代理JAR已复制: $AGENT_JAR"
        else
          echo "警告: 未找到代理JAR文件"
        fi
        
        # 查找并复制前端文件
        FRONTEND_DIR=$(find . -type d -name "web-frontend" | grep -v node_modules | head -1)
        if [ -d "$FRONTEND_DIR/dist" ]; then
          cp -r "$FRONTEND_DIR/dist"/* deploy-package/frontend/
          echo "前端文件已复制"
        else
          echo "警告: 未找到前端dist目录"
        fi
        
        # 查找并复制配置文件
        DEPLOY_DIR=$(find . -type d -name "deploy" | grep -v node_modules | head -1)
        if [ -d "$DEPLOY_DIR" ]; then
          cp "$DEPLOY_DIR/minilpa-backend.service" deploy-package/config/ 2>/dev/null || true
          cp "$DEPLOY_DIR/minilpa-agent.service" deploy-package/config/ 2>/dev/null || true
          cp "$DEPLOY_DIR/nginx.conf.example" deploy-package/config/ 2>/dev/null || true
          cp "$DEPLOY_DIR/update.sh" deploy-package/config/ 2>/dev/null || true
          cp "$DEPLOY_DIR/application-prod.yml" deploy-package/config/application.yml 2>/dev/null || true
          echo "配置文件已复制"
        fi
        
        # 创建部署脚本
        cat > deploy-package/deploy.sh << 'DEPLOYSCRIPT'
        #!/bin/bash
        set -e
        
        INSTALL_DIR="/www/wwwroot/minilpa"
        BACKUP_DIR="$INSTALL_DIR/backup/$(date +%Y%m%d_%H%M%S)"
        
        echo "=== MiniLPA 自动部署脚本 ==="
        
        # 检查是否为root用户
        if [ "$EUID" -ne 0 ]; then 
          echo "请使用 sudo 运行此脚本"
          exit 1
        fi
        
        # 1. 停止服务
        echo "1. 停止服务..."
        systemctl stop minilpa-backend 2>/dev/null || true
        systemctl stop minilpa-agent 2>/dev/null || true
        sleep 2
        
        # 2. 备份旧文件
        echo "2. 备份旧文件..."
        mkdir -p "$BACKUP_DIR"
        if [ -f "$INSTALL_DIR/app/minilpa-backend.jar" ]; then
          cp "$INSTALL_DIR/app/minilpa-backend.jar" "$BACKUP_DIR/" 2>/dev/null || true
        fi
        if [ -f "$INSTALL_DIR/app/minilpa-agent.jar" ]; then
          cp "$INSTALL_DIR/app/minilpa-agent.jar" "$BACKUP_DIR/" 2>/dev/null || true
        fi
        
        # 3. 复制新文件
        echo "3. 复制新文件..."
        mkdir -p "$INSTALL_DIR/app" "$INSTALL_DIR/frontend" "$INSTALL_DIR/config" "$INSTALL_DIR/logs"
        
        # 复制JAR文件
        if [ -f "app/minilpa-backend.jar" ]; then
          cp app/minilpa-backend.jar "$INSTALL_DIR/app/" -f
          echo "   ✅ 后端JAR已更新"
        fi
        if [ -f "app/minilpa-agent.jar" ]; then
          cp app/minilpa-agent.jar "$INSTALL_DIR/app/" -f
          echo "   ✅ 代理JAR已更新"
        fi
        
        # 复制前端文件
        if [ -d "frontend" ]; then
          if [ -d "$INSTALL_DIR/frontend" ]; then
            mv "$INSTALL_DIR/frontend" "$BACKUP_DIR/frontend" 2>/dev/null || true
          fi
          cp -r frontend "$INSTALL_DIR/"
          echo "   ✅ 前端文件已更新"
        fi
        
        # 复制配置文件（可选，不覆盖现有配置）
        if [ -d "config" ]; then
          cp -r config/* "$INSTALL_DIR/config/" 2>/dev/null || true
        fi
        
        # 4. 设置权限
        echo "4. 设置权限..."
        chown -R www:www "$INSTALL_DIR" 2>/dev/null || chown -R $USER:$USER "$INSTALL_DIR"
        chmod 644 "$INSTALL_DIR/app"/*.jar 2>/dev/null || true
        
        # 5. 启动服务
        echo "5. 启动服务..."
        systemctl daemon-reload 2>/dev/null || true
        systemctl enable minilpa-backend 2>/dev/null || true
        systemctl enable minilpa-agent 2>/dev/null || true
        systemctl start minilpa-backend
        systemctl start minilpa-agent
        
        sleep 3
        
        # 检查服务状态
        if systemctl is-active --quiet minilpa-backend; then
          echo "   ✅ 后端服务启动成功"
        else
          echo "   ⚠️  后端服务启动失败"
          echo "   查看日志: sudo journalctl -u minilpa-backend -n 50"
        fi
        
        if systemctl is-active --quiet minilpa-agent; then
          echo "   ✅ 代理服务启动成功"
        else
          echo "   ⚠️  代理服务启动失败"
          echo "   查看日志: sudo journalctl -u minilpa-agent -n 50"
        fi
        
        echo ""
        echo "=== 部署完成 ==="
        echo "备份位置: $BACKUP_DIR"
        DEPLOYSCRIPT
        chmod +x deploy-package/deploy.sh
        
        # 创建压缩包以便传输
        tar -czf deploy-package.tar.gz deploy-package/
        ls -lh deploy-package/
    
    - name: 部署到宝塔服务器
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.BAOTA_HOST }}
        username: ${{ secrets.BAOTA_USER }}
        key: ${{ secrets.BAOTA_SSH_KEY }}
        port: ${{ secrets.BAOTA_SSH_PORT || 22 }}
        source: "deploy-package.tar.gz"
        target: "/tmp"
        strip_components: 1
    
    - name: 解压并执行部署脚本
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BAOTA_HOST }}
        username: ${{ secrets.BAOTA_USER }}
        key: ${{ secrets.BAOTA_SSH_KEY }}
        port: ${{ secrets.BAOTA_SSH_PORT || 22 }}
        script: |
          cd /tmp
          tar -xzf deploy-package.tar.gz
          cd deploy-package
          sudo ./deploy.sh
          rm -rf /tmp/deploy-package /tmp/deploy-package.tar.gz
          echo "部署完成！"
    
    - name: 验证部署
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BAOTA_HOST }}
        username: ${{ secrets.BAOTA_USER }}
        key: ${{ secrets.BAOTA_SSH_KEY }}
        port: ${{ secrets.BAOTA_SSH_PORT || 22 }}
        script: |
          echo "=== 验证服务状态 ==="
          systemctl status minilpa-backend --no-pager -l || true
          systemctl status minilpa-agent --no-pager -l || true

